version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "candidate-crud-http-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1py13qd7axgtm"
s3_prefix = "candidate-crud-http-api"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
